buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0"
        classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.4'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'kotlin'
apply plugin: 'com.github.johnrengelman.shadow'

version = "1.0"
group = "com.futureclient"
archivesBaseName = "FutureClient"

sourceCompatibility = targetCompatibility = 1.8

minecraft {
    version = "1.8.9-11.15.1.1722"
    runDir = "run"
    mappings = "stable_22"
    makeObfSourceJar = false
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.6.0"
}

// Shadow Kotlin into the jar so users don't need a separate library
shadowJar {
    classifier = ''
    configurations = [project.configurations.implementation]
    relocate 'kotlin', 'com.futureclient.shadow.kotlin'
}

reobf {
    shadowJar { mappingType = 'SEARGE' }
}

tasks.build.dependsOn shadowJar
