pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        // REQUIRED: Contains the fabric tools (stitch, mapping-io, fernflower)
        maven { url = "https://maven.fabricmc.net/" }
        // REQUIRED: Contains the forge tools (installertools, binarypatcher)
        maven { url = "https://maven.minecraftforge.net/" }
        // Essential & Architectury repos
        maven { url = "https://repo.essential.gg/repository/maven-public/" }
        maven { url = "https://maven.architectury.dev/" }
    }
}

rootProject.name = 'FutureClient'
