name: Build FutureClient

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # The Runner uses Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Execute Permission
        run: chmod +x gradlew

      # Gradle will detect the toolchain config in build.gradle
      # and auto-download a Java 8 JDK for compilation.
      - name: Build with Gradle
        run: ./gradlew shadowJar --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FutureClient-Jar
          path: build/libs/FutureClient-*-all.jar
